# Generated by Django 5.2.5 on 2025-08-26 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('type', models.CharField(choices=[('studio', 'Studio'), ('appartement', 'Appartement'), ('maison', 'Maison')], default='', max_length=20, verbose_name='Type')),
                ('location', models.CharField(default='Inconnue', max_length=200, verbose_name='Localisation')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Prix')),
                ('bedrooms', models.PositiveIntegerField(default=1, verbose_name='Chambres')),
                ('bathrooms', models.PositiveIntegerField(default=1, verbose_name='Salles de bain')),
                ('area', models.PositiveIntegerField(default=50, verbose_name='Surface (m²)')),
                ('rating', models.FloatField(default=0.0, verbose_name='Note')),
                ('furnished', models.BooleanField(default=False, verbose_name='Meublé')),
                ('available', models.CharField(default='immédiate', max_length=50, verbose_name='Disponibilité')),
                ('contract_duration', models.CharField(choices=[('1', '1 an'), ('2', '2 ans'), ('3', '3 ans'), ('indetermine', 'Durée indéterminée'), ('autre', 'Autre durée')], default='1', max_length=20, verbose_name='Durée de contrat')),
                ('custom_contract_duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='Durée personnalisée')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('wifi', models.BooleanField(default=False, verbose_name='Wi-Fi')),
                ('parking', models.BooleanField(default=False, verbose_name='Parking')),
                ('security', models.BooleanField(default=False, verbose_name='Sécurité')),
                ('pet_friendly', models.BooleanField(default=False, verbose_name='Animaux acceptés')),
                ('state', models.CharField(choices=[('neuf', 'Neuf'), ('excellent', 'Excellent'), ('bon', 'Bon'), ('moyen', 'Moyen')], default='bon', max_length=20, verbose_name='État')),
                ('smoking_allowed', models.BooleanField(default=False, verbose_name='Fumeur autorisé')),
                ('parties_allowed', models.BooleanField(default=False, verbose_name='Fêtes autorisées')),
                ('pets_allowed', models.BooleanField(default=False, verbose_name='Animaux autorisés')),
                ('date_added', models.DateField(default=datetime.date.today, verbose_name="Date d'ajout")),
                ('owner_advance_months', models.PositiveIntegerField(default=3, verbose_name='Acompte propriétaire (mois)')),
                ('agent_fee_months', models.PositiveIntegerField(default=1, verbose_name="Frais d'agence (mois)")),
                ('electricity_deposit', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dépôt électricité')),
                ('water_deposit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dépôt eau')),
                ('other_charges', models.CharField(blank=True, max_length=100, null=True, verbose_name='Autres charges')),
                ('video', models.FileField(blank=True, null=True, upload_to='properties/videos/', verbose_name='Vidéo')),
            ],
            options={
                'verbose_name': 'Propriété',
                'verbose_name_plural': 'Propriétés',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/images/', verbose_name='Image')),
                ('is_main', models.BooleanField(default=False, verbose_name='Image principale')),
            ],
            options={
                'verbose_name': 'Image de propriété',
                'verbose_name_plural': 'Images de propriétés',
            },
        ),
    ]
