# Generated by Django 5.2.5 on 2025-08-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.PositiveIntegerField(default=50, null=True, verbose_name='Surface (m²)'),
        ),
    ]
